
/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Dataset/SegSperm/train
/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Dataset/SegSperm/test_small
GPU dostÄ™pne: NVIDIA GeForce RTX 3090
Traceback (most recent call last):
  File "/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Kod/train.py", line 471, in <module>
    main(model, train_loader, val_loader, optimizer,scheduler, loss_fn, config.epochs,aug,t_aug,save_name)
  File "/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Kod/train.py", line 351, in main
    validation_iou_multiclass,validation_iou_oneclass,vimages,vlbls_multiclass,vlbls_oneclass,vpreds_multiclass,vpreds_oneclass = val(model, validation_loader, loss_fn,epoch_number,scheduler)
                                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Kod/train.py", line 287, in val
    metrics.update_confusion_matrix(vids2.cpu().numpy(), vpreds2.cpu().numpy())
                                                         ^^^^^^^
UnboundLocalError: cannot access local variable 'vpreds2' where it is not associated with a value